### ISSUE TITLE
Kubernetes 中英文词汇标准对应表

### ISSUE THREAD

**Issue by markthink** [kubernetes/kubernetes-docs-zh#122]
## Kubernetes 中英文词汇标准对应表

[Kubernetes 中英文词汇标准对应表](https://docs.google.com/spreadsheets/d/1JXSdoq93J4KnXA3JTQzWvrl2ZbGOMzrWKuyPjEVpUFg/edit#gid=0) 的完善分两步走：

### 第一阶段：在12月31日之前，定一个基础版本的中英文词汇对照表。

先由 @李晶晶-H3C-成都 @宋净超-jimmysong.io @石龙-HandReach-青岛 @时延军-希为科技-北京 @李储强-华为-杭州 @苏楚霖-IBM-深圳 @陈涛-ZTE-三亚 @张琦翔-geniusafc-上海 @邢舟-IBM 一起完善一下中英词汇的标准化，有不同的意见，可以在此留言，默认大家提交的初始化版本，都是采纳状态。

### 第二阶段：在12月31日之后，新词汇的加入方式

元旦之后，新增的词汇，默认都是未采纳状态，每个新增词汇需通过讨论确定最优的翻译结果。

注：初始词汇的翻译邀请是以前期[贡献](https://k8smeetup.github.io/chart/)的顺序排名的..当然未邀请的译者，有兴趣也是可以参与一起完善初始版本的[中英文词汇表]((https://docs.google.com/spreadsheets/d/1JXSdoq93J4KnXA3JTQzWvrl2ZbGOMzrWKuyPjEVpUFg/edit#gid=0) )的，此表并未记名。

我们希望能够保持一份精减，大家容易有岐义的词汇对照表，尽可能给新加入的译者不会造成过多的困惑。

#### 这里会每周同步 Google 词汇表格的更新记录：

kubernetes master node  => kubernetes master节点
kubernetes worker node => kubernetes worker节点
load balancer  => 负载均衡器
API Server => API 服务器
load balance => 负载均衡
runtime => runtime
cloud provider =>云服务提供商
dns entry => dns 条目
control plane => 控制平面

**Comment by xiaosuiba** [comment]
dns entry => dns 条目

**Comment by xiaosuiba** [comment]
Prerequisites => 先决条件

**Comment by zhangxiaoyu-zidif** [comment]
> dns entry => dns 条目
@xiaosuiba  could you list a PR, let me check it. Thanks.

**Comment by pigletfly** [comment]
CPU memory request/limit 的 request/limit 是否需要翻译？

**Comment by chentao1596** [comment]
我觉得可以不用翻译，我这边平时在使用的时候，都是直接用request和limit进行描述

**Comment by pigletfly** [comment]
标点符号是有什么规范吗？中文全角？
