### ISSUE TITLE
Translating some files under user guide

### ISSUE THREAD

**Issue by sn00011** [kubernetes/kubernetes-docs-zh#24]
This is the list i've been working on:
- [x] `docs/user-guide/index.md`
- [x] `docs/user-guide/annotations.md`
- [x]  `docs/user-guide/labels.md`
- [x]  `docs/user-guide/namespaces.md`
- [x]  `docs/user-guide/identifiers.md`
- [x]  `docs/user-guide/pods.md`
- [x]  `docs/user-guide/replication-controller.md`
- [x]  `docs/user-guide/service.md`
- [x]  `docs/user-guide/volumes.md`
- [x]  `docs/user-guide/secrets.md`

The items checked are translated already, once i've finished the list above I will send a pull request by the end of the week soon.

**Comment by iT2afL0rd** [comment]
Please send PR for each file.

**Comment by sn00011** [comment]
@iT2afL0rd : no problem

**Comment by hurf** [comment]
I would prefer you send the translated file first. So other people can get it reviewed earlier. Don't do it all together, people may get tired reviewing too much files at a time.

**Comment by iT2afL0rd** [comment]
@hurf  Agree on it. So if you have finished part, please PR it for review. @kurtzhong

**Comment by sn00011** [comment]
I am currently looking a good way to split the prs, though i've split my work into 10 commits they come out altogether when i am creating the pull requests.

**Comment by iT2afL0rd** [comment]
You can back up your translation. And create 10 branch, each branch with one dedicate translated file.

**Comment by sn00011** [comment]
@iT2afL0rd: Good idea. This is what I end up doing.
