### ISSUE TITLE
Remove the jekyll auto-generated files from repo and ignore them from working directory

### ISSUE THREAD

**Issue by sn00011** [kubernetes/kubernetes-docs-zh#32]
The jekyll auto-generated pages and cache files etc are a little annoying, I think they are better being ignored and not committed into the repo.

**Comment by linfan** [comment]
Those files may NOT be really auto-generated, e.g. the 404 files contains many customised links jumping to contents of k8s docs.

It seems if we want to generate a full web page just same as the official docs website do, we would need those files.
