### ISSUE TITLE
How long will it takes to get the reply?

### ISSUE THREAD

**Issue by jonyhy96** [kubernetes/kubernetes-docs-zh#351]
I already have sent two emails  to  hanjiayao to apply in the translation group.
I just want to know how long will it takes to get the reply.
Thanks.

**Comment by markthink** [comment]
@jonyhy96 您发的是哪个邮箱，我帮您查一下，有可能是掉信了，我们好像没有收到您的邮件。

参考下面的链接：

https://mp.weixin.qq.com/s/1-YYrzEBK8JabxvU93Wf6Q

发邮件给： translator@k8smeetup.com，邮件标题请统一为：K8S 专栏作者

或者将你的 gmail 邮箱和微信号提供给我,我帮你开通..

**Comment by jonyhy96** [comment]
@markthink
感谢您的回复
我是按照 https://docs.google.com/document/d/1xz7BhW8Qkh6reYU7S7RDzSov5e101Vz_fHjq-fEX-W4/edit#heading=h.gjdgxs 这上面的要求发送邮箱给hanjiayao@caicloud.io的

**Comment by jonyhy96** [comment]
@markthink 我已经向translator@k8smeetup.com发送邮件，请查收

**Comment by markthink** [comment]
@jonyhy96 欢迎加入，谢谢。
