### ISSUE TITLE
Some ideas about the contribution on docs-cn repo

### ISSUE THREAD

**Issue by lichuqiang** [kubernetes/kubernetes-docs-zh#76]
1. We need a clear standard for the condition under which  a PR could get merged，say a certain number of guys have reviewed and approved.
2. Commit records might need to be squashed before PR get merged, as we do in k8s repo.
3. We may need to add a list to the CI-robot, which includes the guys who are active in the field of translation. Thus, a new PR could be assigned to one of the guys in the list for review automatically or manually.

Please feel free to give your opinions:)

**Comment by chentao1596** [comment]
say a certain number of guys have reviewed and approved.
*************************
agree +1
And, any certain message should be send to the guys who will merge this PR(like you, ^_^)?
Who is going to do this? The last reviewer?

**Comment by chentao1596** [comment]
say a certain number of guys have reviewed and approved.

**Comment by pigletfly** [comment]
CI-robot is a good idea

**Comment by tianshapjq** [comment]
When exactly should we squash the commits? If after lgtm then this label will be removed after squash, causing another lgtm again.

**Comment by lichuqiang** [comment]
> When exactly should we squash the commits? If after lgtm then this label will be removed after squash, causing another lgtm again.

IMHO, it is not have to be a label, it would be okey if only the author and reviewer reach an agreement on the change, and the reviewer give a clear response that implies his approval of the change.
And when a certain number of guys have reviewed , @chentao1596 ,I think it's the author himself should be the one who ping admin for a merge :)

**Comment by tianshapjq** [comment]
I think if labels like lgtm or others would help the admin to merge, otherwise that would be mountains of works waiting for the admin to update. If lgtm is labeled then the admin just has to merge without taking look into every pr. WDYT?

**Comment by lichuqiang** [comment]
What I'm concerned about is if a contributor have the right to add the label in this repo.
If so, we can certainly make things this way, if not, it means we might need to give lots of guys read/write access to the repo, which is quite dangerous and may drive things out of control.

And no matter which way we take, an admin' task are the same: to receive a signal that implies the PR is ready, do some necessary check, and then a merge. so I think there is no essential difference between the two

**Comment by zhangxiaoyu-zidif** [comment]
we may create a project to track the process of first chinese localization version. and put related pr in it. =)

**Comment by zhangxiaoyu-zidif** [comment]
and if necessary some idea/issue about this repo could be issued by Chinese or bilingual

**Comment by hanjiayao** [comment]
@lichuqiang Oops, I mistakenly deleted a comment from Chuqiang - I meant to say that I agree - the article translator is like a "manager" who should take care of the life cycle of the piece. He/She should be the one who contacted the admin for a merge.
