### ISSUE TITLE
ideas about prioritizing the articles needed to translate

### ISSUE THREAD

**Issue by tianshapjq** [kubernetes/kubernetes-docs-zh#87]
As far, we need to prioritize the articles left to speed up the translation. Here are the principles we had agreement until now:
1. Add a new column including P0-PN in the index table to identify the priorities: P0s are the most urgent tasks, PN can scale from 1-4 (just my opinion).  [**Owner**: TBD]
2. Ignore the auto-generated files at present. Should list all the files. [**Owner**: TBD]
3. Ignore the articles indicating feature has been deprecated. Should list all the files. [**Owner**: TBD]

Any suggestions are welcomed!

@hanjiayao @chentao1596 @linyouchong @zhangxiaoyu-zidif @xiangpengzhao @zhouhaibing089 @lichuqiang @markthink

**Comment by tianshapjq** [comment]
also, do we need to translate the .html files at present?

**Comment by tianshapjq** [comment]
based on the index table, ignoring the under translating, translated and the files under /doc/reference and /doc/resources-reference, we still have 91 files to be translated. As followed:

/docs/admin/admission-controllers.md
/docs/admin/multiple-zones.md
/docs/admin/salt.md
/docs/api-reference/apps/v1beta1/definitions.html
/docs/api-reference/batch/v1/definitions.html
/docs/api-reference/extensions/v1beta1/definitions.html
/docs/api-reference/labels-annotations-taints.md
/docs/api-reference/v1.5/index.html
/docs/api-reference/v1.5/README.md
/docs/api-reference/v1.6/index.html
/docs/api-reference/v1.6/README.md
/docs/api-reference/v1.7/index.html
/docs/api-reference/v1.7/README.md
/docs/api-reference/v1.8/index.html
/docs/api-reference/v1.8/README.md
/docs/concepts/cluster-administration/federation.md
/docs/concepts/cluster-administration/manage-deployment.md
/docs/concepts/cluster-administration/proxies.md
/docs/concepts/example-concept-template.md
/docs/concepts/overview/extending.md
/docs/concepts/storage/persistent-volumes.md
/docs/concepts/storage/storage-classes.md
/docs/concepts/storage/volumes.md
/docs/concepts/workloads/pods/podpreset.md
/docs/contribute/README.md
/docs/getting-started-guides/alibaba-cloud.md
/docs/getting-started-guides/alternatives.md
/docs/getting-started-guides/centos/centos_manual_config.md
/docs/getting-started-guides/clc.md
/docs/getting-started-guides/coreos/bare_metal_offline.md
/docs/getting-started-guides/docker-multinode.md
/docs/getting-started-guides/docker.md
/docs/getting-started-guides/fedora/fedora_ansible_config.md
/docs/getting-started-guides/fedora/fedora_manual_config.md
/docs/getting-started-guides/fedora/flannel_multi_node_cluster.md
/docs/getting-started-guides/libvirt-coreos.md
/docs/getting-started-guides/mesos-docker.md
/docs/getting-started-guides/mesos/index.md
/docs/getting-started-guides/openstack-heat.md
/docs/getting-started-guides/ovirt.md
/docs/getting-started-guides/ubuntu/operational-considerations.md
/docs/getting-started-guides/ubuntu/scaling.md
/docs/getting-started-guides/ubuntu/security.md
/docs/getting-started-guides/ubuntu/troubleshooting.md
/docs/getting-started-guides/ubuntu/upgrades.md
/docs/getting-started-guides/ubuntu/validation.md
/docs/home/contribute/style-guide.md
/docs/home/contribute/write-new-topic.md
/docs/home/index.md
/docs/search.md
/docs/setup/independent/troubleshooting-kubeadm.md
/docs/setup/index.md
/docs/sitemap.md
/docs/tabs-example.md
/docs/tasks/administer-federation/cluster.md
/docs/tasks/administer-federation/configmap.md
/docs/tasks/administer-federation/daemonset.md
/docs/tasks/administer-federation/deployment.md
/docs/tasks/administer-federation/hpa.md
/docs/tasks/configure-pod-container/security-context.md
/docs/tasks/debug-application-cluster/audit.md
/docs/tasks/debug-application-cluster/debug-application-introspection.md
/docs/tasks/debug-application-cluster/debug-application.md
/docs/tasks/debug-application-cluster/debug-cluster.md
/docs/tasks/debug-application-cluster/debug-pod-replication-controller.md
/docs/tasks/federation/federation-service-discovery.md
/docs/tasks/federation/set-up-coredns-provider-federation.md
/docs/tasks/federation/set-up-placement-policies-federation.md
/docs/tasks/inject-data-application/define-command-argument-container.md
/docs/tasks/job/coarse-parallel-processing-work-queue/index.md
/docs/tasks/job/fine-parallel-processing-work-queue/index.md
/docs/tasks/job/parallel-processing-expansion.md
/docs/tasks/manage-daemon/update-daemon-set.md
/docs/tasks/run-application/run-replicated-stateful-application.md
/docs/tasks/run-application/run-single-instance-stateful-application.md
/docs/tasks/run-application/scale-stateful-set.md
/docs/tutorials/clusters/apparmor.md
/docs/tutorials/configuration/configure-redis-using-configmap.md
/docs/tutorials/index.md
/docs/tutorials/stateless-application/expose-external-ip-address.md
/docs/user-guide/configmap/README.md
/docs/user-guide/downward-api/README.md
/docs/user-guide/kubectl/v1.6/README.md
/docs/user-guide/kubectl/v1.7/index.html
/docs/user-guide/kubectl/v1.7/README.md
/docs/user-guide/kubectl/v1.8/index.html
/docs/user-guide/kubectl/v1.8/README.md
/docs/user-guide/liveness/image/README.md
/docs/user-guide/update-demo/images/kitten/README.md
/docs/user-guide/update-demo/images/nautilus/README.md
/docs/user-guide/update-demo/local/index.html

any suggestions to narrow down the list?

**Comment by linyouchong** [comment]
have you check the website/cn directory?

**Comment by tianshapjq** [comment]
@linyouchong no, the list is just based on the index table in google drive. What should I note from that directory?

**Comment by tianshapjq** [comment]
ignoring those have been assigned, here are the files needs to translate with highest priority:

/docs/api-reference/labels-annotations-taints.md
/docs/api-reference/v1.5/README.md
/docs/api-reference/v1.6/README.md
/docs/api-reference/v1.7/README.md
/docs/api-reference/v1.8/README.md
**/docs/concepts/cluster-administration/federation.md**  (exists in website/cn repo)
**/docs/concepts/workloads/pods/podpreset.md**  (exists in website/cn repo)
/docs/getting-started-guides/alibaba-cloud.md
/docs/getting-started-guides/fedora/fedora_manual_config.md
/docs/getting-started-guides/fedora/flannel_multi_node_cluster.md
/docs/getting-started-guides/libvirt-coreos.md
/docs/getting-started-guides/mesos/index.md
/docs/getting-started-guides/ovirt.md
/docs/home/contribute/style-guide.md
/docs/home/contribute/write-new-topic.md
/docs/home/index.md
/docs/setup/independent/troubleshooting-kubeadm.md
/docs/setup/index.md
/docs/tabs-example.md
/docs/tasks/administer-federation/cluster.md
/docs/tasks/administer-federation/configmap.md
/docs/tasks/administer-federation/daemonset.md
/docs/tasks/administer-federation/deployment.md
/docs/tasks/administer-federation/hpa.md
/docs/tasks/federation/federation-service-discovery.md
/docs/tasks/federation/set-up-coredns-provider-federation.md
/docs/tasks/federation/set-up-placement-policies-federation.md
/docs/user-guide/downward-api/README.md
/docs/user-guide/kubectl/v1.6/README.md
/docs/user-guide/kubectl/v1.7/README.md
/docs/user-guide/kubectl/v1.8/README.md

@hanjiayao wish it would help, maybe you can add a new column in the index table and tag these to P0, noting that we have to tanslate these in prior. 
Question is: there are still lots of files in "not started" status, how can we be sure they will be finished on time?
on the other hand, federation.md and podpreset.md already exist in the website/cn repo, do we need to translate again?

**Comment by hanjiayao** [comment]
@tianshapjq yes, like we discussed yesterday, I think we should just go ahead to prioritize the most important ones and label them in the index. 

For "not-started" ones, i'd say if idled longer than 10 days, we'd send a reminder to check the status and if not taken care of, we shall just remove the tag and let others take that piece.

**Comment by xiangpengzhao** [comment]
> ignoring those have been assigned, here are the files needs to translate with highest priority:

I'd suggest we ignore these pre-1.8 docs:
```
/docs/api-reference/v1.5/README.md
/docs/api-reference/v1.6/README.md
/docs/api-reference/v1.7/README.md

/docs/user-guide/kubectl/v1.6/README.md
/docs/user-guide/kubectl/v1.7/README.md
```

**Comment by xiangpengzhao** [comment]
Actually, 1.5 is no longer a supported version in the current release cycle. And 1.6 won't be supported any more as well after 1.9 is cut.

```
Kubernetes has a X.Y.Z versioning scheme, where X is the major version, Y is the minor version, and Z is the patch version.
Kubernetes is supported for three minor versions at a time. This includes the current release version and two previous versions.
```

Quoted from the chapter `Supported Versions` in https://kubernetes.io/docs/home/
